#! /usr/bin/env bash

hyprctl -j activeworkspace | jq -c

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do 
  hyprctl -j activeworkspace | jq -c
done
