#! /usr/bin/env bash

hyprctl -j workspaces | jq -c 'sort_by(.id)'

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do 
  hyprctl -j workspaces | jq -c 'sort_by(.id)'
done
