keys:
  - &kiesen age1jawf28hfe053j36mnhx6x390ahqtxu0auapwrgvflyf5sq4ts9fs5exzdj
  - &graphite age1srp2swq6j626qteytq2jcrm3yj0z65rj67th88psfxajdt2hdgts4jksse
  - &halite age103crd20yg40h3clw55l9h28k5fvfuxx8y9vl4xqruczuy4h53gqs4c85qp
  - &flourite age1u2qunqqvv0krjvsru69wxguy74xz87fntf2yy8w6v4kspa6ayceqj3av0y
creation_rules:
  - path_regex: shared.yaml
    key_groups:
    - age:
      - *kiesen
      - *graphite
      - *halite
      - *flourite
  - path_regex: kiesen.yaml
    key_groups:
    - age:
      - *kiesen
  - path_regex: graphite.yaml
    key_groups:
    - age:
      - *kiesen
      - *graphite
  - path_regex: halite.yaml
    key_groups:
    - age:
      - *kiesen
      - *halite
