#!/usr/bin/env bash

cd "$HOME"

mkdir -p .config

# clone down nvchad if nvim is installed, and no config exists
# if command -v nvim > /dev/null 2>&1; then
#   echo "nvim detected"
#   if [ ! -d .config/nvim/.git ]; then 
#     echo "Installing nvchad..."
#     git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
#   else
#     echo "nvim config already exists"
#   fi 
#   if [ ! -d .config/nvim/lua/custom ]; then
#     ln -s ~/.config/nvchad ~/.config/nvim/lua/custom
#   fi
# fi

# sparse checkout
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md'

# setup doom emacs if available
if command -v .config/emacs/bin/doom >/dev/null 2>&1; then
    echo "Bootstrapping Doom Emacs..."

    doom=".config/emacs/bin/doom"
    $doom upgrade
    $doom sync
fi

