#!/bin/bash

# multiply the factor by that amount
# 0 will reset zoom

echo $1

if [[ $1 -eq 0 ]];
then
    echo "reset zoom"
    hyprctl keyword misc:cursor_zoom_factor 1.0
else
    echo "changing zoom"
    zoom_str=$(hyprctl getoption misc:cursor_zoom_factor | grep float)
    echo "got zoom"
    echo "zoom_str: $zoom_str"
    echo "getting number"
    curr_zoom=${zoom_str#*:}
    echo "curr_zoom: $curr_zoom"
    echo "getting new zoom"
    new_zoom=$(bc <<< "$curr_zoom * $1")
    echo "new_zoom: $new_zoom"
    if [[ $(bc <<< "$new_zoom < 1.0") == 1 ]]; then
        echo "setting min zoom"
        hyprctl keyword misc:cursor_zoom_factor 1.0
    else
        echo "setting new zoom"
        hyprctl keyword misc:cursor_zoom_factor $new_zoom
    fi
fi

